project:
  type: website
  output-dir: docs
prefer-html: true

toc: true 
number-sections: true
website:
  title: "Exportações de Vinhos do Brasil"
  navbar:
    search: true
    background: primary
    tools:
    - icon: github
      menu:
        - text: Source Code
          url: https://github.com/carlosvneves/fiap_techchallenge01
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Contexto"
        file: context.qmd
      - text: "Análises"  
        menu: 
          - text: "Análise exploratória"
            file: explore.qmd
          - text: "Análise das séries temporais agregadas"
            file: tsanalysis.qmd
          - text: "Análise das séries temporais - Paraguai e Rússia"
            file: tsanalysistop.qmd
          - text: "Análise das séries temporais - interações"
            file: exogenous.qmd   
        
book:
  title: "Análise das Exportações de Vinhos do Brasil - Techchallenge 01 - 3DTAT - FIAP"
  author: "Carlos Eduardo Veras Neves"
  date: "1/29/2024"
  chapters:
    - index.qmd
    - context.qmd
    - explore.qmd
    - tsanalysis.qmd
    - tsanalysistop.qmd
    - exogenous.qmd

  page-footer:
    left: |
      Exportações de Vinhos do Brasil - 3DTAT - FIAP
    right: |
      Este livro foi construído com <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg


format:
  html:
    grid: 
      body-width: 1080px
      sidebar-width: 350px
    theme:
      light: 
           - lux
           - custom.scss
      dark: darkly
  epub:
    cover-image: cover.jpg