project:
  type: book
  output-dir: _output

toc: true 
number-sections: true

book:
  title: "Análise das Exportações de Vinhos do Brasil - Techchallenge 01 - 3DTAT - FIAP"
  author: "Carlos Eduardo Veras Neves"
  date: "1/29/2024"
  chapters:
    - index.qmd
    - context.qmd
    #- exploratory_yearly.qmd
    # - exploratory_monthly.qmd
    # - analysis.qmd
    # - conclusion.qmd
  page-footer:
    left: |
      Exportações de Vinhos do Brasil - 3DTAT - FIAP
    right: |
      Este livro foi construído com <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
# bibliography: refs.bib

format:
  html:
    grid: 
      body-width: 1080px
      sidebar-width: 350px
    theme:
      light: 
           - lux
           - custom.scss
      dark: darkly
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.jpg